name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set lowercase image name
        run: |
          IMAGE=$(echo "${{ secrets.DOCKER_USERNAME }}/quotes-api:${{ github.sha }}" | tr '[:upper:]' '[:lower:]')
          echo "DOCKER_IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t "$DOCKER_IMAGE" .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push image
        run: docker push "$DOCKER_IMAGE"

      - name: Set up kubeconfig
        run: echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig.yaml

      - name: Deploy to Kubernetes
        run: |
          export KUBECONFIG=kubeconfig.yaml
          kubectl set image deployment/quotes-api quotes-api="$DOCKER_IMAGE"